Project project_name {
  database_type: 'PostgreSQL'
  Note: 'Pocketlink.co.uk'
}

// authentication and password / email reset
Ref auth_method_used: users.auth_type_id - auth_types.id [delete: restrict]
Ref token_owner: password_reset_tokens.user_id > users.id [delete: cascade]
Ref token_owner: email_change_tokens.user_id > users.id [delete: cascade]
Ref token_owner: user_verification_tokens.user_id > users.id [delete: cascade]

// domains & short links
Ref domain_owner: domains.user_id > users.id [delete: restrict]
Ref short_link_owner: short_links.user_id > users.id [delete: restrict]
Ref short_link_domain: short_links.domain_id - domains.id [delete: restrict]

// audit events & link visits
Ref audit_event_owner: audit_events.user_id > users.id [delete: set null]
Ref type_of_audit_event: audit_events.audit_event_type_id - audit_event_types.id [delete: restrict]
Ref visits_for_short_link: link_visits.short_link_id > short_links.id [delete: set null]

Table domains {
  id bigint [pk, unique, not null, increment]
  user_id bigint [null]
  name varchar [unique, not null]
  is_default boolean [not null]
  created_at timestamptz [not null]
  updated_at timestamptz [not null]
  deleted_at timestamptz [null]

  indexes {
    (user_id, is_default) [unique, note: 'Where is_default = true']
  }

}

Table users {
  id bigint [pk, unique, not null, increment]
  auth_type_id bigint [not null]
  email varchar [unique, not null]
  max_allowed_links integer [not null]
  password_hash varchar [null]
  display_name varchar [null]
  created_at timestamptz [not null]
  updated_at timestamptz [not null]
  deleted_at timestamptz [null]
  verified_at timestamptz [null]
}

Table short_links {
  id bigint [pk, unique, not null, increment]
  user_id bigint [not null]
  domain_id bigint [not null]
  title varchar [null]
  destination_url varchar [not null]
  back_half varchar [not null]
  created_at timestamptz [not null]
  updated_at timestamptz [not null]
  deleted_at timestamptz [null]

  indexes {
    (domain_id, back_half) [unique]
  }

}

Table archived_short_links {
  back_half varchar [not null]
  domain_name varchar [not null]
  created_at timestamptz [not null]
  updated_at timestamptz [not null]

  indexes {
    (domain_name, back_half) [pk, unique]
  }

}

Table password_reset_tokens {
  id bigint [pk, unique, not null, increment]
  user_id bigint [not null]
  primary_token_hash varchar [not null, unique]
  secondary_token_hash varchar [null]
  primary_token_used_at timestamptz [null]
  secondary_token_used_at timestamptz [null]
  created_at timestamptz [not null]
  expires_at timestamptz [not null]
}


// TODO: proof read how this will work
Table email_change_tokens {
  id bigint [pk, unique, not null, increment]
  user_id bigint [not null]
  new_email varchar [not null]
  authorisation_token_hash varchar [not null, unique]
  verification_token_hash varchar [null]
  authorisation_token_used_at timestamptz [null]
  verification_token_used_at timestamptz [null]
  created_at timestamptz [not null]
  expires_at timestamptz [not null]
}

Table user_verification_tokens {
  id bigint [pk, unique, not null, increment]
  user_id bigint [not null]
  token_hash varchar [not null, unique]
  created_at timestamptz [not null]
  expires_at timestamptz [not null]
}

Table auth_types {
  id bigint [pk, unique, not null, increment]
  name varchar [not null, unique]
  created_at timestamptz [not null]
  updated_at timestamptz [not null]
  deleted_at timestamptz [null]
}

Table audit_event_types {
  id bigint [pk, unique, not null, increment]
  name varchar [not null, unique]
  created_at timestamptz [not null]
  updated_at timestamptz [not null]
  deleted_at timestamptz [null]
}

Table audit_events {
  id bigint [pk, unique, not null, increment]
  user_id bigint [null]
  audit_event_type_id bigint [not null]
  body jsonb [not null]
  created_at timestamptz [not null]
}

Table link_visits {
  id bigint [pk, unique, not null, increment]
  short_link_id bigint [not null]
  user_agent varchar [null]
  location_country varchar [null]
  location_region varchar [null]
  location_city varchar [null]
  referrer varchar [null]
  created_at timestamptz [not null]
}
